### ISSUE TITLE
add connecting to pg from Evidence.dev guide

### ISSUE THREAD

**Issue by ChuckHend** [tembo-io/website#672]
Provide guide for connecting to tembo using evidence.dev. 

Example connection yaml below

// connection.yaml
```yaml
name: tembo
type: postgres
options:
  host: hilariously.suspicious.imposter.data-1.use1.tembo.io
  port: 5432
  database: postgres
  ssl:
    sslmode: require
    rejectUnauthorized: false
  schema: public
  connectionString: postgresql://postgres:XXX@hilariously.suspicious.imposter.data-1.use1.tembo.io:5432/postgres?sslmode=verify-full&sslrootcert=ca.crt
```
